import type { Database } from '../../types/database'

export type SiteContent = Database['public']['Tables']['site_content']['Row']

export type SiteContentFormValues = Omit<SiteContent, 'id' | 'updated_at'>

export function siteContentToFormValues(content: SiteContent): SiteContentFormValues {
  return {
    hero_kicker: content.hero_kicker,
    hero_headline: content.hero_headline,
    hero_subtext: content.hero_subtext,
    hero_cta_primary_label: content.hero_cta_primary_label,
    hero_cta_secondary_label: content.hero_cta_secondary_label,
    hero_image_url: content.hero_image_url,
    hero_video_url: content.hero_video_url,
    about_eyebrow: content.about_eyebrow,
    about_title: content.about_title,
    about_body: content.about_body,
    mission_title: content.mission_title,
    mission_body: content.mission_body,
    vision_title: content.vision_title,
    vision_body: content.vision_body,
    philosophy_eyebrow: content.philosophy_eyebrow,
    philosophy_title: content.philosophy_title,
    philosophy_body: content.philosophy_body,
    services_summary_eyebrow: content.services_summary_eyebrow,
    services_summary_title: content.services_summary_title,
    services_summary_body: content.services_summary_body,
    portfolio_eyebrow: content.portfolio_eyebrow,
    portfolio_title: content.portfolio_title,
    portfolio_button_label: content.portfolio_button_label,
    about_page_eyebrow: content.about_page_eyebrow,
    about_page_title: content.about_page_title,
    about_page_description: content.about_page_description,
    about_story_eyebrow: content.about_story_eyebrow,
    about_story_title: content.about_story_title,
    about_story_body: content.about_story_body,
    about_story_image_url: content.about_story_image_url,
    values_eyebrow: content.values_eyebrow,
    values_title: content.values_title,
    process_eyebrow: content.process_eyebrow,
    process_title: content.process_title,
    process_body: content.process_body,
    services_page_eyebrow: content.services_page_eyebrow,
    services_page_title: content.services_page_title,
    services_page_description: content.services_page_description,
    services_cta_eyebrow: content.services_cta_eyebrow,
    services_cta_heading: content.services_cta_heading,
    services_cta_button_label: content.services_cta_button_label,
    contact_page_eyebrow: content.contact_page_eyebrow,
    contact_page_title: content.contact_page_title,
    contact_page_description: content.contact_page_description,
    stats: content.stats ?? [],
    services: content.services ?? [],
    testimonials: content.testimonials ?? [],
    values: content.values ?? [],
    process_steps: content.process_steps ?? [],
  }
}
